import { describe, it, expect } from 'vitest';
import { generateLean, leanExpr, leanProp, definitionOrder } from '../generate.js';
import { assignLeanNames } from '../names.js';
import { defaults, square } from '../../diagram/__tests__/fixtures.js';
import { markCommuting } from '../../diagram/commute.js';
import { addGoal } from '../../math/proof.js';
import { emptyDocument, declareObject, declareMorphism, declareHypothesis } from '../../math/context.js';
import { setMorphismDefinition } from '../../math/definitions.js';
import { morphism, identity, compose } from '../../math/expr.js';

const f = morphism('f'), g = morphism('g'), h = morphism('h'), k = morphism('k');

/** Level I-4 with the square marked and its equation as a goal. */
function i4() {
  const s = markCommuting(square(), 'A', 'D');
  return addGoal(s.doc, { kind: 'eq', left: compose(f, h), right: compose(g, k) }, 'goal:I-4:g1')[0];
}

/** The editor defaults with a goal saying the composite arrow is the composite. */
function trianglе() {
  const d = defaults();
  return addGoal(d.doc, { kind: 'eq', left: morphism('f3'), right: compose(morphism('f1'), morphism('f2')) }, 'g1')[0];
}

const I4_SOURCE = `-- generated by CATS; do not edit by hand.
import Mathlib.CategoryTheory.Category.Basic

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

open CategoryTheory

universe u v

section CATS

variable {𝒞 : Type u} [Category.{v} 𝒞]
variable {A B C D : 𝒞}
variable (f : A ⟶ B) (g : A ⟶ C) (h : B ⟶ D) (k : C ⟶ D)

-- goal:I-4:g1 : f ≫ h = g ≫ k  (CATS: entailed by h₁)
example (h₁ : f ≫ h = g ≫ k) : f ≫ h = g ≫ k := by
  first | rfl | (simp_all only [Category.assoc, Category.id_comp, Category.comp_id]; done) | aesop_cat

end CATS
`;

const TRIANGLE_SOURCE = `-- generated by CATS; do not edit by hand.
import Mathlib.CategoryTheory.Category.Basic

set_option autoImplicit false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

open CategoryTheory

universe u v

section CATS

variable {𝒞 : Type u} [Category.{v} 𝒞]
variable {A B C : 𝒞}
variable (f : A ⟶ B) (g : B ⟶ C)
local notation "gf" => f ≫ g

-- g1 : gf = f ≫ g  (CATS: holds by definition)
example : gf = f ≫ g := by
  first | rfl | (simp_all only [Category.assoc, Category.id_comp, Category.comp_id]; done) | aesop_cat

end CATS
`;

describe('leanExpr', () => {
  const names = assignLeanNames(square().doc.context);

  it('writes composition in diagrammatic order', () => {
    expect(leanExpr(names, compose(f, h))).toBe('f ≫ h');
  });

  it('writes an identity the Mathlib way', () => {
    expect(leanExpr(names, identity('A'))).toBe('𝟙 A');
  });

  it('parenthesizes a nested composition', () => {
    expect(leanExpr(names, compose(f, compose(h, morphism('k'))))).toBe('f ≫ (h ≫ k)');
  });

  it('prints a proposition as an equation', () => {
    expect(leanProp(names, { kind: 'eq', left: compose(f, h), right: compose(g, k) })).toBe('f ≫ h = g ≫ k');
  });
});

describe('generateLean', () => {
  it('generates the I-4 square exactly, with its line map', () => {
    const gen = generateLean(i4());
    expect(gen.source).toBe(I4_SOURCE);
    expect(gen.goals).toEqual([{ id: 'goal:I-4:g1', startLine: 19, line: 20, endLine: 21 }]);
    // The line map points at the real lines.
    const lines = gen.source.split('\n');
    expect(lines[gen.goals[0]!.line - 1]).toMatch(/^example /);
    expect(lines[gen.goals[0]!.startLine - 1]).toMatch(/^-- goal:I-4:g1/);
  });

  it('generates the defaults triangle exactly, defining the composite as a notation', () => {
    const gen = generateLean(trianglе());
    expect(gen.source).toBe(TRIANGLE_SOURCE);
    expect(gen.goals).toEqual([{ id: 'g1', startLine: 20, line: 21, endLine: 22 }]);
  });

  it('says what CATS believes above each goal', () => {
    const believed = generateLean(i4()).source;
    expect(believed).toContain('(CATS: entailed by h₁)');

    // The same square without the equation: CATS cannot say anything.
    const open = addGoal(square().doc, { kind: 'eq', left: compose(f, h), right: compose(g, k) }, 'q1')[0];
    expect(generateLean(open).source).toContain('(CATS: not entailed by CATS; Lean decides)');

    // A unit law is a category axiom, not a definition.
    let doc = square().doc;
    [doc] = addGoal(doc, { kind: 'eq', left: compose(identity('A'), f), right: f }, 'q2');
    expect(generateLean(doc).source).toContain('(CATS: holds by the category axioms)');
  });

  it('emits an identity loop as a notation', () => {
    let doc = emptyDocument();
    [doc] = declareObject(doc, { name: 'A' }, 'A');
    [doc] = declareMorphism(doc, { name: '\\mathrm{id}_A', source: 'A', target: 'A' }, 'loop');
    doc = setMorphismDefinition(doc, 'loop', identity('A'));
    [doc] = addGoal(doc, { kind: 'eq', left: morphism('loop'), right: identity('A') }, 'q1');
    const source = generateLean(doc).source;
    expect(source).toContain('local notation "id_A" => 𝟙 A');
    expect(source).toContain('example : id_A = 𝟙 A := by');
  });

  it('omits the morphism variable line when every morphism is defined', () => {
    let doc = emptyDocument();
    [doc] = declareObject(doc, { name: 'A' }, 'A');
    [doc] = declareMorphism(doc, { name: '\\mathrm{id}_A', source: 'A', target: 'A' }, 'loop');
    doc = setMorphismDefinition(doc, 'loop', identity('A'));
    expect(generateLean(doc).source).not.toContain('variable (');
  });

  it('records that there is nothing to prove when a context has no goals', () => {
    expect(generateLean(square().doc).source).toContain('-- no goals: the context itself is the statement.');
    expect(generateLean(square().doc).goals).toEqual([]);
  });

  it('skips a hypothesis that says nothing', () => {
    let doc = square().doc;
    [doc] = declareHypothesis(doc, { prop: { kind: 'eq', left: compose(f, h), right: compose(f, h) } }, 'triv');
    [doc] = addGoal(doc, { kind: 'eq', left: compose(f, h), right: compose(f, h) }, 'q1');
    expect(generateLean(doc).source).toContain('example : f ≫ h = f ≫ h := by');
  });

  it('filters to the requested goals', () => {
    let doc = i4();
    [doc] = addGoal(doc, { kind: 'eq', left: f, right: f }, 'q2');
    expect(generateLean(doc).goals.map(b => b.id)).toEqual(['goal:I-4:g1', 'q2']);
    const one = generateLean(doc, { goalIds: ['q2'] });
    expect(one.goals.map(b => b.id)).toEqual(['q2']);
    expect(one.source).not.toContain('goal:I-4:g1');
  });

  it('is deterministic', () => {
    expect(generateLean(i4()).source).toBe(generateLean(i4()).source);
  });
});

describe('definitionOrder', () => {
  it('puts a definition after the definitions it depends on', () => {
    let doc = emptyDocument();
    for (const o of ['A', 'B', 'C']) [doc] = declareObject(doc, { name: o }, o);
    // `x` is declared before its factors and is defined through `y`, which is
    // itself defined: declaration order would emit the notations backwards.
    [doc] = declareMorphism(doc, { name: 'x', source: 'A', target: 'C' }, 'x');
    [doc] = declareMorphism(doc, { name: 'y', source: 'A', target: 'B' }, 'y');
    [doc] = declareMorphism(doc, { name: 'p', source: 'A', target: 'B' }, 'p');
    [doc] = declareMorphism(doc, { name: 'q', source: 'B', target: 'C' }, 'q');
    doc = setMorphismDefinition(doc, 'y', morphism('p'));
    doc = setMorphismDefinition(doc, 'x', compose(morphism('y'), morphism('q')));
    expect(definitionOrder(doc.context).map(m => m.id)).toEqual(['y', 'x']);

    const lines = generateLean(doc).source.split('\n').filter(l => l.startsWith('local notation'));
    expect(lines).toEqual(['local notation "y" => p', 'local notation "x" => y ≫ q']);
  });

  it('is empty when nothing is defined', () => {
    expect(definitionOrder(square().doc.context)).toEqual([]);
  });
});
