/**
 * The mathematical IR as a Lean 4 / Mathlib file.
 *
 * One section holds the whole context: objects as implicit variables, atomic
 * morphisms as explicit ones, and defined morphisms as `local notation`, so a
 * composite arrow *is* its composite (`gf = f ≫ g` by `rfl`) with no argument
 * bookkeeping. Each goal becomes one `example` carrying the hypotheses it may
 * use as binders, because a section variable that appears only inside a tactic
 * block is not included in the statement.
 *
 * The comment above each goal records what CATS itself believes; the `example`
 * below it is what Lean will decide. Those are different claims and the file
 * shows both (development plan §17).
 */
import type {
  GoalId, MathContext, MathDocument, MorphismDecl, MorphismExpr, Proposition,
} from '../math/types.js';
import { assertNever } from '../math/types.js';
import { MathError, objectsOf, morphismsOf, hypothesesOf } from '../math/context.js';
import { exprEquals, mentions } from '../math/expr.js';
import { unfold, exprKey } from '../math/unfold.js';
import { entailment } from '../math/entail.js';
import { assignLeanNames } from './names.js';
import type { LeanNames } from './names.js';

/** Where one goal sits in the generated file. Lines are 1-based and inclusive. */
export interface LeanGoalBlock {
  id: GoalId;
  /** The comment line above the example. */
  startLine: number;
  /** The `example` line itself. */
  line: number;
  /** The last line of the proof. */
  endLine: number;
}

export interface GeneratedLean {
  source: string;
  goals: LeanGoalBlock[];
  names: LeanNames;
}

export interface GenerateOptions {
  /** Restrict to these goals (used for the per-goal source stored on a step). */
  goalIds?: GoalId[];
}

/**
 * One tactic, so one Lean run decides the goal. `rfl` catches definitional
 * equalities (a notation unfolds to its body); `simp_all` normalizes the goal
 * *and* the hypotheses with the category axioms, which handles chains of
 * equations in either orientation without us guessing a rewrite direction;
 * `aesop_cat` is Mathlib's categorical finisher and does the congruence
 * reasoning that `entails` deliberately refuses to do.
 */
const PROOF = 'first | rfl | (simp_all only [Category.assoc, Category.id_comp, Category.comp_id]; done) | aesop_cat';

const HEADER = [
  '-- generated by CATS; do not edit by hand.',
  'import Mathlib.CategoryTheory.Category.Basic',
  '',
  'set_option autoImplicit false',
  'set_option linter.unusedVariables false',
  // The proof tries several tactics and keeps the first that works, so the
  // alternatives it never reaches are expected, not a mistake.
  'set_option linter.unusedTactic false',
  'set_option linter.unreachableTactic false',
  '',
  'open CategoryTheory',
  '',
  'universe u v',
  '',
  'section CATS',
  '',
];

function nameOf(names: LeanNames, id: string): string {
  return names.byId.get(id) ?? id;
}

/** `f ≫ g`, `𝟙 A`. Nested compositions are parenthesized; `≫` is right-associative. */
export function leanExpr(names: LeanNames, e: MorphismExpr): string {
  switch (e.kind) {
    case 'morphism':
      return nameOf(names, e.ref);
    case 'identity':
      return `𝟙 ${nameOf(names, e.object)}`;
    case 'compose':
      return e.factors
        .map(f => (f.kind === 'compose' ? `(${leanExpr(names, f)})` : leanExpr(names, f)))
        .join(' ≫ ');
    default:
      return assertNever(e);
  }
}

export function leanProp(names: LeanNames, p: Proposition): string {
  switch (p.kind) {
    case 'eq':
      return `${leanExpr(names, p.left)} = ${leanExpr(names, p.right)}`;
    default:
      return assertNever(p.kind);
  }
}

/**
 * Defined morphisms with their dependencies first. A definition may reference a
 * declaration that comes later in the context, so declaration order will not do;
 * `validateContext` guarantees the graph is acyclic.
 */
export function definitionOrder(ctx: MathContext): MorphismDecl[] {
  const defined = morphismsOf(ctx).filter(m => m.definition !== undefined);
  const byId = new Map(defined.map(m => [m.id, m]));
  const out: MorphismDecl[] = [];
  const done = new Set<string>();
  const visiting = new Set<string>();

  const visit = (m: MorphismDecl): void => {
    if (done.has(m.id)) return;
    if (visiting.has(m.id)) throw new MathError(`circular definition through '${m.name || m.id}'`);
    visiting.add(m.id);
    for (const other of defined) {
      if (other.id !== m.id && mentions(m.definition!, new Set([other.id]))) visit(byId.get(other.id)!);
    }
    visiting.delete(m.id);
    done.add(m.id);
    out.push(m);
  };

  for (const m of defined) visit(m);
  return out;
}

/** What CATS itself can say about a goal, for the comment above it. */
function verdict(ctx: MathContext, names: LeanNames, prop: Proposition): string {
  const result = entailment(ctx, prop);
  if (!result.holds) return 'not entailed by CATS; Lean decides';
  if (result.by.length > 0) return `entailed by ${result.by.map(id => nameOf(names, id)).join(', ')}`;
  return exprEquals(unfold(ctx, prop.left), unfold(ctx, prop.right))
    ? 'holds by definition'
    : 'holds by the category axioms';
}

/** Comments must stay on one line or they swallow the code below them. */
function oneLine(s: string): string {
  return s.replace(/\s+/g, ' ').trim();
}

export function generateLean(doc: MathDocument, opts: GenerateOptions = {}): GeneratedLean {
  const ctx = doc.context;
  const names = assignLeanNames(ctx);
  const lines: string[] = [...HEADER];

  lines.push(`variable {${names.category} : Type u} [Category.{v} ${names.category}]`);

  const objects = objectsOf(ctx);
  if (objects.length > 0) {
    lines.push(`variable {${objects.map(o => nameOf(names, o.id)).join(' ')} : ${names.category}}`);
  }

  const defined = definitionOrder(ctx);
  const definedIds = new Set(defined.map(m => m.id));
  const atomic = morphismsOf(ctx).filter(m => !definedIds.has(m.id));
  if (atomic.length > 0) {
    const binders = atomic
      .map(m => `(${nameOf(names, m.id)} : ${nameOf(names, m.source)} ⟶ ${nameOf(names, m.target)})`)
      .join(' ');
    lines.push(`variable ${binders}`);
  }
  for (const m of defined) {
    lines.push(`local notation "${nameOf(names, m.id)}" => ${leanExpr(names, m.definition!)}`);
  }

  // A hypothesis that is trivially true after unfolding carries no information
  // and would only give `simp_all` a useless rewrite.
  const hypotheses = hypothesesOf(ctx).filter(h => exprKey(ctx, h.prop.left) !== exprKey(ctx, h.prop.right));
  const binders = hypotheses
    .map(h => `(${nameOf(names, h.id)} : ${leanProp(names, h.prop)})`)
    .join(' ');

  const wanted = opts.goalIds ? doc.goals.filter(g => opts.goalIds!.includes(g.id)) : doc.goals;
  const goals: LeanGoalBlock[] = [];

  if (wanted.length === 0) {
    lines.push('');
    lines.push('-- no goals: the context itself is the statement.');
  }

  for (const goal of wanted) {
    lines.push('');
    // `lines.length` after a push is that line's 1-based number.
    lines.push(`-- ${goal.id} : ${oneLine(leanProp(names, goal.prop))}  (CATS: ${verdict(ctx, names, goal.prop)})`);
    const startLine = lines.length;
    lines.push(`example ${binders ? `${binders} ` : ''}: ${leanProp(names, goal.prop)} := by`);
    const line = lines.length;
    lines.push(`  ${PROOF}`);
    goals.push({ id: goal.id, startLine, line, endLine: lines.length });
  }

  lines.push('');
  lines.push('end CATS');
  lines.push('');

  return { source: lines.join('\n'), goals, names };
}
