export const st = {
  panel: {
    width: 240,
    background: '#0c1220',
    borderRight: '1px solid #1a2540',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    flexShrink: 0,
  },
  panelHdr: {
    padding: '13px 16px 10px',
    fontSize: 10,
    letterSpacing: '0.13em',
    textTransform: 'uppercase',
    color: '#3d5a8a',
    borderBottom: '1px solid #1a2540',
    fontFamily: "'JetBrains Mono', monospace",
    flexShrink: 0,
  },
  panelFoot: {
    padding: '10px 12px',
    borderTop: '1px solid #1a2540',
    flexShrink: 0,
  },
  list: {
    flex: 1,
    overflowY: 'auto',
    padding: '6px 0',
  },
  item: (active) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    padding: '7px 12px',
    cursor: 'pointer',
    background: active ? '#162038' : 'transparent',
    borderLeft: `3px solid ${active ? '#4db8ff' : 'transparent'}`,
    transition: 'background 0.1s',
  }),
  btn: {
    background: '#162038',
    border: '1px solid #1e3256',
    color: '#4db8ff',
    padding: '7px 14px',
    cursor: 'pointer',
    fontSize: 11,
    fontFamily: "'JetBrains Mono', monospace",
    letterSpacing: '0.05em',
    borderRadius: 4,
    transition: 'background 0.12s',
  },
  btnActive: {
    background: '#1a3a6a',
    border: '1px solid #2a5498',
    color: '#64b5f6',
    padding: '7px 14px',
    cursor: 'pointer',
    fontSize: 11,
    fontFamily: "'JetBrains Mono', monospace",
    letterSpacing: '0.05em',
    borderRadius: 4,
  },
  input: {
    background: '#0a1020',
    border: '1px solid #1e3256',
    color: '#c8d3ea',
    padding: '4px 8px',
    fontSize: 13,
    borderRadius: 4,
    width: '100%',
    fontFamily: "'Crimson Text', Palatino, serif",
    fontStyle: 'italic',
    outline: 'none',
    boxSizing: 'border-box',
  },
  select: {
    background: '#0a1020',
    border: '1px solid #1e3256',
    color: '#c8d3ea',
    padding: '4px 8px',
    fontSize: 11,
    borderRadius: 4,
    width: '100%',
    fontFamily: "'JetBrains Mono', monospace",
    outline: 'none',
    boxSizing: 'border-box',
  },
  xBtn: {
    background: 'none',
    border: 'none',
    color: '#3d5a8a',
    cursor: 'pointer',
    fontSize: 16,
    lineHeight: 1,
    padding: '0 2px',
    flexShrink: 0,
  },
  empty: {
    padding: '24px 16px',
    color: '#2d4070',
    fontSize: 11,
    fontFamily: 'monospace',
    textAlign: 'center',
    lineHeight: 1.8,
  },
};
